language: c

compiler:

  - gcc

before_install:

  - sudo apt-get update
  
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
  
install:

  - echo "Reached install section"
  
script:

  - echo "Reached Script Section"
 # - gcc hello_world.c -o output
 # - ./output  

  - echo "compiling main.c"
  - gcc j_practice.c  main.c -o output
  - ./output

  - echo "compiling j_test.c"
  - gcc j_test.c -o output -lcunit
  - ./output
